### ISSUE TITLE
Add direct support for package:pageloader

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular_test#11]
Want some input here.

I'd like minimal/no-boiler when using `pageloader` with `angular_test`, but I want to be careful about creating this dependency instead of an `angular_pageloader` package or something else. Internally we handle this dependency through our 3-letter pattern group, so this is mostly an external-only question.

**Comment by natebosch** [comment]
IMO it would be ok to take on a dependency to pageloader. I think there are benefits to having the test package be opinionated about these types of things.
