### ISSUE TITLE
Should we plan on supporting Build/Bazelify?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular_test#18]
My current plan for this package is have the `1.0.0` beta target the `3.0.0` beta of AngularDart.

That means, as of today, we'd only be targeting transformers - so I'm planning on spending a bit of time on https://github.com/dart-lang/angular_test/issues/13 to help users add the appropriate annotations and configuration to their pubspec as part of this package - it's very easy to miss a single step and get screwed.

Questions:

1. Should we plan on supporting a `pkg:build|build_runner` for AngularDart by 3.0.0?

2. Should we plan on supporting `bazel_codegen` for AngularDart by 3.0.0?

3. Any other considerations I might have missed?

**Comment by natebosch** [comment]
What is the timeline for 3.0.0?
Ideally it would be good to support `bazel_codegen`, but I'm not sure we should make it a blocker.

I wouldn't think it should be a breaking change to add in support, so maybe it doesn't matter too much?

**Comment by matanlurey** [comment]
No public timeline :) 

Just deciding if I should spend too much time on #13 or not.

**Comment by natebosch** [comment]
I think it's worthwhile to support transformers and pub as fully as we would without bazel codegen for now.

**Comment by matanlurey** [comment]
Sg. Closing for now.
