### ISSUE TITLE
Bump required version of AngularDart to 3.0.0-alpha

### ISSUE THREAD

**Issue by tomas-rokos** [dart-lang/angular_test#21]
I started to play with angular_test and wasn't successful with more then one test, the second always crashed with EXCEPTION: Bad state: Cannot fire new event. Controller is already firing an event.

By playing more the key problem is that angular_test package depends on version ^2.0.0 of angular2, but in texts it always says the it's for v3, when I locally change that, it works now.

**Comment by matanlurey** [comment]
Closed via #22
