### ISSUE TITLE
Figure out why `pub run angular_test` fails on Travis

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular_test#23]
See https://travis-ci.org/dart-lang/angular_test/jobs/197890698#L717

**Comment by matanlurey** [comment]
Hard to say. Is this is a port issue? Content-shell issue? Does `dartium` work?

/cc @kevmoo

**Comment by kevmoo** [comment]
See https://travis-ci.org/dart-lang/angular_test/builds/199286886

**Comment by kevmoo** [comment]
I haven't figured out much after a bit of digging.

I'm wondering if pub is blowing up here: https://travis-ci.org/dart-lang/angular_test/jobs/199309111#L713

related to pkg/http_multi_server

**Comment by matanlurey** [comment]
Closed since I don't see this anymore.

**Comment by kevmoo** [comment]
Re-enabled with 1347c0ee973c3dea26845be0d845cd94c0c48d6c
