### ISSUE TITLE
Optionally hide/display pub serve outputs

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/angular_test#26]
The `stdout` and `stderr` output of pub serve "spams" the console output, I find it difficult to find relevant information about tests. I can imagine a couple of ways to remedy this:

1. pipe output of pub serve to temporary file and print file path when tests are started
2. ignore stdout messages, only show error messages (build errors are relevant)
3. have a `--verbose` option to package:angular_test that will include all pub serve output, otherwise do not display them

**Comment by matanlurey** [comment]
Was closed by #41 I believe.
