### ISSUE TITLE
Pub serve (test compiler) should use a random port

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/angular_test#29]
I think it would be prettier if `pub serve` bound itself to a random port and that was used by tests. 

[package:test](/dart-lang/test/blob/0.12.11+x/test/io.dart) has an example how reading the random port can be done using package:scheduled_test. 
I imagine it shouldn't be much more difficult to do something similar without scheduled_test (especially given that it will be deprecated).

**Comment by matanlurey** [comment]
Closes by https://github.com/dart-lang/angular_test/pull/28

**Comment by daniel-v** [comment]
I will assume, this is closed because of your comment of "forward all unrecognized or trailing flags to package:test".

I am wondering how that will solve this. I imagine 2 port related use-cases:

- during development, there is a pub serve running in the background on a port I know, I want to pass it to package:test and instruct angular_test not to start a server in the background (to speed running things up)
- on a CI/test server, where many tests can run at once, in which case the package:angular_test itself should make the determination of the port binding (usually indicated by 0).

In the latter case, I'd bind on port `0`, and serve would print out the actual port it runs on. That should be picked up and used by pacakge:test.

Did I miss something? Are these use-cases going to be supported?

**Comment by matanlurey** [comment]
Looking for a volunteer to do this one, maybe @daniel-v - I won't have time to get it to it immediately.

**Comment by daniel-v** [comment]
I can get to it, probably this weekend (if someone else won't send in a PR earlier :wink: @valakis)

**Comment by daniel-v** [comment]
PR is in.
