### ISSUE TITLE
Do not check in angular_test with transformers: ...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular_test#32]
Due to lack of something like `dev_transformers`, the new sync of AngularDart (https://github.com/dart-lang/angular2/issues/272) is blocked. I can do the following to get around that:

1. Remove the `transformers: ...` section
2. In `tool/presubmit.sh`, append that section back before running
3. Do not check in a `transformers: ...` section in the future

**Comment by zoechi** [comment]
can https://github.com/dart-lang/pub/issues/1260#issuecomment-163065340 help here?

**Comment by matanlurey** [comment]
Ooh it might. I'll try that out
