### ISSUE TITLE
ngOnChanges is not called before ngOnInit

### ISSUE THREAD

**Issue by tomas-rokos** [dart-lang/angular_test#44]
I found one problem I was having by depending on ngOnChanges. Based on documentation https://webdev.dartlang.org/angular/guide/lifecycle-hooks the hook ngOnChanges is called before ngOnInit.

But this is not happening when creating by NgTestBed. Would be nice to fix it to make test and production environment more similar.

Thank you,
Tomáš

**Comment by matanlurey** [comment]
We are not doing anything special in `NgTestBed` compared to Angular in production (it runs the same code). Could you share a reproduction case for me @tomas-rokos?

**Comment by tomas-rokos** [comment]
[Archiv.zip](https://github.com/dart-lang/angular_test/files/887749/Archiv.zip)
Hi Matan,
here is a created sample. If you run web/index.html you will see in console: 

```
Observatory listening at http://127.0.0.1:56610/
ngOnChanges
ngOnInit

```
which is correct based on documentation. I have component with Input parameter so I get ngOnChanges before ngOnInit and also after every Input change.
If you run test/index.html where I test the component, you will get:
```
Observatory listening at http://127.0.0.1:57068/
00:00 [32m+0[0m: playground[0m
ngOnInit
ngOnDestroy
00:00 [32m+1[0m: All tests passed![0m

```
There is addition of ngOnDestroy since  I call disposeAnyRunningTest() and it destroys that component, but you see that there is no ngOnChanges before ngOnInit.

This is not critical problem, I found it when writing test for one of my component and it internally depended on having ngOnChanges before ngOnInit. I put explicit call to ngOnChanges at the end of  beforeChangeDetection and it works fine. However I think that you should think about this as regular issue when writing tests for Components with Inputs. I understand that term beforeChangeDetection explicitly says that it is BEFORE, but in production the component gets call in ngOnChanges before ngOnInit and it looks to me as potential hole in testing. Where production might crash, but tests are all OK.

Thank you,
Tomáš

**Comment by matanlurey** [comment]
So I investigated this - and I'm going to add a test case as an example, but in this case you are creating a test fixture directly around `NestedComponent` - this is strongly not recommended - instead create `AppComponent`, and set its `name` parameter.

Change detection will pick it up and propagate it to the child, calling the events in the correct order. You're correct that `beforeChangeDetection` is specific - because this is basically a (non-observed) hook to let you set properties on the _root_ component with the expectation they propagate downwards. As an example until I send the PR:

```dart
// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

@Tags(const ['aot'])
@TestOn('browser')
import 'dart:html';

import 'package:angular2/angular2.dart';
import 'package:angular_test/angular_test.dart';
import 'package:test/test.dart';

@AngularEntrypoint()
void main() {
  Element docRoot;
  Element testRoot;

  setUp(() {
    docRoot = new Element.tag('doc-root');
    testRoot = new Element.tag('ng-test-bed-example-test');
    docRoot.append(testRoot);
  });

  tearDown(disposeAnyRunningTest);

  test('should render, update, and destroy a component', () async {
    // We are going to verify that the document root has a new node created (our
    // component), the node is updated (after change detection), and after
    // destroying the test the document root has been cleared.
    final testBed = new NgTestBed<AngularLifecycle>(host: testRoot);
    final fixture = await testBed.create();
    expect(docRoot.text, isEmpty);
    await fixture.update((c) => c.value = 'New value');
    expect(docRoot.text, 'New value');
    await fixture.dispose();
    expect(docRoot.text, isEmpty);
  });

  test('should invoke ngOnChanges, then ngOnInit', () async {
    final fixture = await new NgTestBed<NgOnChangesInitOrder>().create(
      beforeChangeDetection: (root) => root.name = 'Hello',
    );
    await fixture.query<ChildWithLifeCycles>(
      (el) => el.componentInstance is ChildWithLifeCycles,
      (child) {
        expect(child.events, ['OnChanges:name=Hello', 'OnInit']);
      },
    );
  });
}

@Component(
  selector: 'test',
  template: '{{value}}',
)
class AngularLifecycle {
  String value = '';
}

@Component(
  selector: 'test',
  directives: const [ChildWithLifeCycles],
  template: '<child [name]="name"></child>',
)
class NgOnChangesInitOrder {
  String name;
}

@Component(
  selector: 'child',
  template: '',
)
class ChildWithLifeCycles implements OnChanges, OnInit {
  final events = <String>[];

  @Input()
  String name = '';

  @override
  void ngOnChanges(_) {
    events.add('OnChanges:name=$name');
  }

  @override
  void ngOnInit() {
    events.add('OnInit');
  }
}
```
