### ISSUE TITLE
Hangs after tests ran - process never returns

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/angular_test#56]
On windows, running `pub run angular_test` hangs and never returns. I've attached some pics to better explain what happens.

While tests are running, this is the process tree:
![while_running](https://cloud.githubusercontent.com/assets/2668320/24828894/b7aa4866-1c67-11e7-96ae-e9dd14d29902.png)

After tests ran, this is what I see in console:
![console](https://cloud.githubusercontent.com/assets/2668320/24828897/c83f1ec2-1c67-11e7-95ab-e53d17df1f86.PNG)

At that point, we still have a `dart` process, just chilling, waiting for something.
![when_hung](https://cloud.githubusercontent.com/assets/2668320/24828900/d8ff2892-1c67-11e7-8ddb-9cf5f9b9d9f5.png)

**Comment by daniel-v** [comment]
I can offer a workaround so `package:angular_test` does not hang, however that is a fix.

What's your take on this @matanlurey, would you like me to?

**Comment by matanlurey** [comment]
Sure @daniel-v !

**Comment by matanlurey** [comment]
I *think* this is fixed now upstream after a new release.
