### ISSUE TITLE
Got error "Failed to load..." when pub run angular_test

### ISSUE THREAD

**Issue by tfzhu** [dart-lang/angular_test#62]
I tried to run test for this project. But got error:

The pub serve output is at file:///tmp/angular_test_pub_serve_output.log
Finished AoT compilation. Running tests...
00:00 +0: loading test/bootstrap_test.dart
00:00 +0 -1: loading test/bootstrap_test.dart [E]

Failed to load "test/bootstrap_test.dart": Failed to run Content Shell: Content Shell failed with exit code 1..

Content of /tmp/angular_test_pub_serve_output.log
Loading source assets...

Loading angular2/transform/codegen, angular2/transform/reflection_remover and test/pub_serve transformers...
Serving angular_test test on http://localhost:8080
[test] GET Served 2 assets.
[test] GET Served 4 assets.

It may related with my configuration:
Dart version: Dart VM version: 1.23.0 (Fri Apr 21 03:09:30 2017) on "linux_x64"

**Comment by matanlurey** [comment]
Are you still seeing this issue?

**Comment by tfzhu** [comment]
Thanks. Problem solved, but I don't know why, maybe related with dart update.
