### ISSUE TITLE
Can't run tests under Dart 1.24

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_test#63]
Attempting to run the very simple tests of the [AngularDart docs quickstart](https://github.com/angular-examples/quickstart) results in a never ending stream of "loading test/app_test.dart":
```nocode
quickstart > pub run angular_test
The pub serve output is at file:///var/folders/xm/_v98y69x26v2fqdmr2wtxd3w0000gn/T/angular_test_pub_serve_output.log
Finished AoT compilation. Running tests...
00:00 +0: loading test/app_test.dart
00:01 +0: loading test/app_test.dart
00:02 +0: loading test/app_test.dart
00:03 +0: loading test/app_test.dart
00:04 +0: loading test/app_test.dart
...
```
The same tests run fine under 1.23.

Cf. https://github.com/google/stagehand/issues/422#issuecomment-305910869

cc @kwalrath @kevmoo @matanlurey

**Comment by chalin** [comment]
Update: tests are running under Travis (Ubuntu linux), but the problem persists when I attempt to run the tests locally, under MacOS.

**Comment by kevmoo** [comment]
We should try this again – w/ an updated pkg/test.

I think some of the logic has improved...

**Comment by chalin** [comment]
I have been using the updated test package (0.12.21	Jun 5, 2017):
```
quickstart > pub upgrade
Resolving dependencies... (10.2s)
  analyzer 0.30.0+2
  angular2 3.1.0
  angular_test 1.0.0-beta+2
...
  test 0.12.21    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  typed_data 1.1.3
  unittest 0.11.7 (0.12.4+1 available)
...
  yaml 2.1.12
No dependencies changed. <<<<<<<<<<<<<<<<<<<<<<<<<<<<
```
Under 1.24RC0
```
quickstart > dart --version
Dart VM version: 1.24.0-dev.6.8 (Mon Jun  5 15:26:29 2017) on "macos_x64"
quickstart > pub --version
Pub 1.24.0-dev.6.8
```
Running the angular_tests results in:
```
quickstart > pub run angular_test
The pub serve output is at file:///var/folders/xm/_v98y69x26v2fqdmr2wtxd3w0000gn/T/angular_test_pub_serve_output.log
Finished AoT compilation. Running tests...
00:00 +0: loading test/app_test.dart
00:01 +0: loading test/app_test.dart
00:02 +0: loading test/app_test.dart
...
00:39 +0: loading test/app_test.dart
00:40 +0: loading test/app_test.dart
...
```
Whereas running the same tests w/ dartium results in:
```
quickstart > pub run angular_test --platform=dartium
The pub serve output is at file:///var/folders/xm/_v98y69x26v2fqdmr2wtxd3w0000gn/T/angular_test_pub_serve_output.log
Finished AoT compilation. Running tests...
00:00 +0: loading test/app_test.dart
00:01 +0: loading test/app_test.dart
00:02 +0: loading test/app_test.dart
00:03 +0: loading test/app_test.dart
00:04 +0: loading test/app_test.dart
00:05 +0: loading test/app_test.dart
00:05 +0: test/app_test.dart: Default greeting
00:06 +0: test/app_test.dart: Default greeting
00:06 +1: test/app_test.dart: Default greeting
00:06 +1: test/app_test.dart: Greet world
00:06 +2: test/app_test.dart: Greet world HTML                                                     
00:06 +3: test/app_test.dart: Greet world HTML
00:06 +3: All tests passed!
```

**Comment by kevmoo** [comment]
:-/

**Comment by kwalrath** [comment]
I'm seeing the same behavior. Dartium works, content shell doesn't. Doesn't matter whether you're using dartdevc or dart2js.

**Comment by grouma** [comment]
So the root cause is an issue with package:test on Mac. It is getting stuck in this loop here: https://github.com/dart-lang/test/blob/master/lib/src/runner/browser/content_shell.dart#L62

My guess is that the console message is different on Mac for some reason. I'll need to figure out a solution and release a new version of package test. As of right now, I don't think this is a specific issue with the SDK, just how we are handling the new version of content-shell.

**Comment by grouma** [comment]
Looks like we can't parse the standard error of content shell since it boots up with the following error: 
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

@terrylucas have you seen this issue before?

**Comment by grouma** [comment]
Please pub upgrade to resolve the issue.

**Comment by chalin** [comment]
Yes, it works, thanks!
